### ISSUE TITLE
Is this driver production ready?

### ISSUE THREAD

**Issue by AcaDemIQ** [pascomnet/nomad-driver-podman#19]
This driver is describing on site: https://nomadproject.io/docs/drivers/external/podman/
On README.md file, this driver is Not production ready.

Where is true?)

**Comment by onlyjob** [comment]
IMHO notion of production readiness is not too useful. Whatever technologies are going to be used in "production", one have to test their combination thoroughly anyway and decide whether they are good enough.

So far I had only positive experience with Nomad-driver-Podman and recently we've started to use if for some essential services.

Podman driver is better maintained and more mature than Singularity driver (which have no "not-production-ready" warning).

**Comment by towe75** [comment]
@AcaDemIQ it has, for now, this statement on the website because i (the initial developer) am not using it at scale. The first few lines where written as a proof-of-concept for both the podman and nomad communities. 

Users like @onlyjob report bugs and file feature requests and, when time comes, decide about the "rediness" for production. Just give it a try and see if it fits your requirements. Would be nice if you can drop me a note about your experience with nomad and this driver. 

Ok to close this issue?
